name: rtd-environment
channels:
- conda-forge
dependencies:
- alabaster==0.7.13
- Babel==2.12.1
- backcall==0.2.0
- certifi==2022.12.7
- chardet==4.0.0
- cycler==0.10.0
- Cython==0.29.33
- decorator==5.1.1
- docutils==0.18.1
- idna==3.4
- imagesize==1.4.1
- ipython==8.11.0
- jedi==0.18.2
- Jinja2==3.1.2
- kiwisolver==1.4.4
- MarkupSafe==2.1.2
- matplotlib==3.7.1
- numpy==1.24.2
- numpydoc==1.5.0
- packaging==23.0
- parso==0.8.3
- pexpect==4.8.0
- pickleshare==0.7.5
- Pillow==9.4.0
- prompt-toolkit==3.0.38
- ptyprocess==0.7.0
- Pygments==2.14.0
- pyparsing==3.0.9
- python-dateutil==2.8.2
- pytz==2023.3
- requests==2.28.2
- scipy==1.10.1
- six==1.16.0
- snowballstemmer==2.2.0
- Sphinx==6.1.3
- sphinx-gallery==0.12.2
- sphinx-rtd-theme==1.2.0
- sphinxcontrib-applehelp==1.0.4
- sphinxcontrib-bibtex==2.5.0
- sphinxcontrib-devhelp==1.0.2
- sphinxcontrib-htmlhelp==2.0.1
- sphinxcontrib-jsmath==1.0.1
- sphinxcontrib-qthelp==1.0.3
- sphinxcontrib-serializinghtml==1.1.5
- suitesparse
- traitlets==5.9.0
- urllib3==1.26.14
- wcwidth==0.2.6
- wheel==0.38.4
- pip
- pip:
  - ..[full]
